config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :legal_texts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # custom public views
  # root "front#index"
  root "front#maintenance"

  # resources

  # authentication

  # API

  # custom notifications
  # get '/notice', to: 'post#clear_message'
  # Custom error pages
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/legal_text.rb
class LegalText < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_rich_text :content
  validates_presence_of :title, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index
  end

  def maintenace 
  end
end

app/controllers/legal_texts_controller.rb
class LegalTextsController < ApplicationController
  before_action :set_legal_text, only: %i[ show edit update destroy ]

  # GET /legal_texts or /legal_texts.json
  def index
    @legal_texts = LegalText.all
  end

  # GET /legal_texts/1 or /legal_texts/1.json
  def show
  end

  # GET /legal_texts/new
  def new
    @legal_text = LegalText.new
  end

  # GET /legal_texts/1/edit
  def edit
  end

  # POST /legal_texts or /legal_texts.json
  def create
    @legal_text = LegalText.new(legal_text_params)

    respond_to do |format|
      if @legal_text.save
        format.html { redirect_to legal_text_url(@legal_text), notice: "Legal text was successfully created." }
        format.json { render :show, status: :created, location: @legal_text }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @legal_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legal_texts/1 or /legal_texts/1.json
  def update
    respond_to do |format|
      if @legal_text.update(legal_text_params)
        format.html { redirect_to legal_text_url(@legal_text), notice: "Legal text was successfully updated." }
        format.json { render :show, status: :ok, location: @legal_text }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @legal_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legal_texts/1 or /legal_texts/1.json
  def destroy
    @legal_text.destroy

    respond_to do |format|
      format.html { redirect_to legal_texts_url, notice: "Legal text was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_legal_text
      @legal_text = LegalText.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def legal_text_params
      params.require(:legal_text).permit(:title, :content, :position, :slug)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.turbo_stream # add format turbo_stream
        format.html { redirect_to posts_path }
        format.json { render :show, status: :created, location: @post }
      else
        format.turbo_stream # add format turbo_stream
        format.html { render posts_path, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.turbo_stream # add format turbo_stream
        format.html { redirect_to posts_path, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.turbo_stream # add format turbo_stream
        format.html { render posts_path, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.turbo_stream # add format turbo_stream
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def clear_message
    respond_to do |format|
      format.turbo_stream
    end 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :meta_title, :meta_description, :position, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  NOTICE = {
    create: 'Post created successfully',
    update: 'Post updated successfully',
    delete: 'Post deleted successfully',
    error: 'Something went wrong'
  }.freeze

  def notice_stream(message:, status:)
    turbo_stream.replace 'notice', partial: 'notice', locals: { notice: NOTICE[message], status: status }
  end

  def form_post_stream(post:)
    turbo_stream.replace 'form', partial: 'form', locals: { post: post }
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/front/index.html.erb
<div id="options" data-controller="visibility">
  <h1>Toggle Visibility</h1>
  
  <button data-action="visibility#showTargets" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Show All Elements</button>
  <button data-action="visibility#hideTargets" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Hide All Elements</button>
  <button data-action="visibility#toggleTargets" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Toggle Element Visibility</button>
    
  <p data-visibility-target="hideable">The Flamboyent Thing #1<p/>
  <p data-visibility-target="hideable" hidden>The Slightly Stealthy Thing #2<p/>
</div>

app/views/front/maintenance.html.erb
<div class="flex flex-col justify-center items-center mx-auto">
  <%= link_to inline_svg_tag('ciscolegrandlogo.svg', size:'250px',class: 'self-center text-lg font-semibold whitespace-nowrap dark:text-white'), root_path, class: 'flex'%>

  <%= inline_svg_tag('content/night.svg',size: '70%', class: 'mx-8')%>


  <p class="text-1xl mx-8">Thank you for coming this far,  but we are still building this website</p>
  <%#= link_to 'blog', blorgh_path, class: 'button is-success is-large' %>
  <p class="flex flex-col items-center">  <span class="text-1xl mx-3">Contact:</span>  <br>
  <a href="mailto:cisco.glez@gmail.com" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm mx-8 px-4 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">cisco.glez@gmail.com</a>
  <br>
  <a href="https://github.com/ciscoLegrand/" target="_blank" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm mx-8  px-4 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
    <%= inline_svg_tag('icons/ico-github.svg', class: 'mx-3')%>
    ciscoLegrand
  </a>
  </p>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CBase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <% if 1 == 0 %>
      <%= render 'layouts/partials/navigation' %>
      <%= turbo_frame_tag :notice, class: 'w-full' do %>
      <% end %> 
    <% end %>
    
    <main class="container mx-auto min-h-screen  mt-8 mb-8 px-5 flex" style="min-height: 60vh;">
      <%= yield %>
    </main>
    <%#= render 'layouts/partials/footer' %>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
    <footer class="border-t border-gray-200">
      <div class="container flex flex-col flex-wrap  px-4 py-16 mx-auto md:items-center lg:items-start md:flex-row md:flex-nowrap">
        <div class="flex-shrink-0 w-64 mx-auto text-center md:mx-0 md:text-left" >
          <%= link_to inline_svg_tag('ciscolegrandlogo.svg', size:'80px',class: 'self-center text-lg font-semibold whitespace-nowrap dark:text-white'), root_path , class:"flex items-center justify-center text-4xl font-bold text-blue-700 md:justify-start"%>
        </div>
        <div class="justify-between w-full mt-4 text-center lg:flex">          
          <% if LegalText.first.present? %>         
            <div class="w-full px-4 lg:w-1/3 md:w-1/2">
              <h2 class="mb-2 font-bold tracking-widest text-gray-900">
                Apartados legales
              </h2>
              <ul class="mb-8 space-y-2 text-sm list-none">
                <% LegalText.all.each do |legal| %>
                  <li> <%= link_to legal.title, legal, class: 'text-gray-600 hover:text-gray-800' %> </li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
      <div class="flex justify-center">
        <p class="text-base text-gray-400">
          All rights reserved by @ company 2021
        </p>
      </div>
    </footer>

app/views/layouts/partials/_navigation.html.erb
<nav class="border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800 shadow-lg">
  <div class="container flex flex-wrap justify-between items-center mx-auto">
    <%= link_to inline_svg_tag('ciscolegrandlogo.svg', size:'80px',class: 'self-center text-lg font-semibold whitespace-nowrap dark:text-white'), root_path, class: 'flex'%>
    <div class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1" id="mobile-menu-2">
      <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <li> <%= link_to 'Home', root_path, class: 'block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700' %> </li>
        <li>
          <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
        </li>
        <li>
          <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Pricing</a>
        </li>
        <li>
          <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/legal_texts/_form.html.erb
<%= form_with(model: legal_text, class: "contents") do |form| %>
  <% if legal_text.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(legal_text.errors.count, "error") %> prohibited this legal_text from being saved:</h2>

      <ul>
        <% legal_text.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full h-96" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/legal_texts/_legal_text.html.erb
<div id="<%= dom_id legal_text %>">
  <h1 class="text-6xl font-normal leading-normal mt-0 mb-2"> <%= legal_text.title %> </h1>

  <p class="my-5">
    <%= raw legal_text.content %>
  </p>

  <% if action_name != "show" %>
    <p class="my-5">
      Created: <%= time_tag legal_text.created_at, "data-local": "time-ago" %>
    </p>
    <%= link_to "Show this legal text", legal_text, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this legal text', edit_legal_text_path(legal_text), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/legal_texts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing legal text</h1>

  <%= render "form", legal_text: @legal_text %>

  <%= link_to "Show this legal text", @legal_text, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to legal texts", legal_texts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/legal_texts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Legal texts</h1>
    <%= link_to 'New legal text', new_legal_text_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="legal_texts" class="min-w-full">
    <%= render @legal_texts %>
  </div>
</div>

app/views/legal_texts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New legal text</h1>

  <%= render "form", legal_text: @legal_text %>

  <%= link_to 'Back to legal texts', legal_texts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/legal_texts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @legal_text %>
  </div>
</div>

app/views/posts/_form.html.erb
  <%= turbo_frame_tag dom_id post do %>
    <%= form_with(
      model: post, 
      id: 'form',
      class: "contents",
      html: {
        data: { controller: 'notice', action: 'submit->notice#clear' }
      }
    ) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :content %>
      <%= form.rich_text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full h-96" %>
    </div>

    <div class="my-5">
      <%= form.label :meta_title %>
      <%= form.text_field :meta_title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :meta_description %>
      <%= form.text_area :meta_description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :position %>
      <%= form.number_field :position, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
<% end %>

app/views/posts/_notice.html.erb
<p class="animate-pulse opacity-80 w-full py-2 px-3 bg-<%= status %>-50 mb-5 text-<%= status %>-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= post.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= raw post.content %>
  </p>
  
  
  <% if action_name != "show" %>
    <p class="my-5">
      <strong class="block font-medium mb-1">Meta title:</strong>
      <%= post.meta_title %>
    </p>
    <p class="my-5">
      <strong class="block font-medium mb-1">Meta description:</strong>
      <%= post.meta_description %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Position:</strong>
      <%= post.position %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Posted:</strong>
      <%= time_tag post.created_at, "data-local": "time-ago" %>
    </p>

    <%= link_to "Show this post", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this post', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/posts/clear_message.turbo_stream.erb
<%= turbo_stream.replace 'notice' do %>
  <%= turbo_frame_tag :notice %>
<% end %>
  

app/views/posts/create.turbo_stream.erb
 <% if @post.errors.present? %>
   <%= notice_stream(message: :error, status: 'red') %>
   <%= form_post_stream(post: @post) %>
<% else %>
   <%= notice_stream(message: :create, status: 'green') %>

   <%= turbo_stream.replace :new_post do %>
      <%= turbo_frame_tag :new_post %>
   <% end %>

   <%= turbo_stream.prepend 'posts', partial: 'post', locals: { post: @post } %>

 <% end %>

app/views/posts/destroy.turbo_stream.erb
  <%= notice_stream(message: :delete, status: 'green') %>
  <%= turbo_stream.remove @post %>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="text-white text-lg font-bold text-4xl">Posts</h1>
    <%= link_to 'New post', new_post_path,
      class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium",
      data: { 'turbo-frame': 'new_post' }
    %>
  </div>

  <%= turbo_frame_tag :new_post %>

  <div class="min-w-full">
    <%= turbo_frame_tag :posts do %>
      <%= render @posts %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag :new_post do %>
  <div class="w-full bg-white p-4 rounded-md mt-4">
    <h1 class="text-lg font-bold text-4xl">New post</h1>

    <%= render "form", post: @post %>

    <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>
<%= turbo_frame_tag dom_id(@post) do %>
  <div class="container bg-white p-2 rounded-md mt-2">
  <div class="w-full bg-white rounded-md p-4 justify-start mt-2">
    <h1 class="text-lg font-bold text-4xl">
      <%= @post.title %>
    </h1>
    <p class="my-5 inline-block">
      <%= @post.content.truncate(27, separator: ' ') %>
    </p>

    <%= link_to 'Edit this post', edit_post_path(@post), class: "mt-2 rounded-lg p-2 bg-green-500 inline-block font-medium text-white" %>
      <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg p-2 bg-gray-300 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Delete this post', post_path(@post), method: :delete, data: { controller: 'confirm', confirm_message_value: 'Deseja remover ?', action: 'click->confirm#dialog' }, class: "mt-2 text-white rounded-lg p-2 bg-red-500 font-medium" %>
    </div>
  </div>



<% end %>

app/views/posts/update.turbo_stream.erb
   <% if @post.errors.present? %>
     <%= notice_stream(message: :error, status: 'red') %>
     <%= form_post_stream(post: @post) %>
   <% else %>
     <%= notice_stream(message: :update, status: 'green') %>
     <%= turbo_stream.replace dom_id(@post), partial: 'post', locals: { post: @post } %>
   <% end %>